version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - chmod +x gradlew
      - ./gradlew build
  post_build:
    commands:
      - echo Build completed on `date`
      - ls -al build/libs
      - ls -al build/distributions
artifacts:
  files:
    - build/distributions/samy.zip
    - appspec.yml
  discard-paths: yes
